<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);
$NO_REDIRECT = 1;
require_once("includes/common_front.php");


global $hash;

$secret_key = "12BDCC6A131F4D0292F336C2E2D785E1";
$access_code="103774d5-d771-4e37-83ac-2d70abfa980e";              
                                          
function Hex2String($hex)
{
    $string='';
    
    for ($i=0; $i < strlen($hex)-1; $i+=2)
    {
        $string .= chr(hexdec($hex[$i].$hex[$i+1]));
    }
    
    return $string;
}
                                          

$data = [
  "merchant_data"=> [
      "merchant_id"=> "325765",
      "merchant_access_code"=> "$access_code",
      "merchant_return_url"=> "https://royalcabsgoa.com/webhook_plural.php",
      "unique_merchant_txn_id"=> "Rddd887823"
    ],
    "payment_data"=> [
      "amount_in_paisa"=> 1000
      
    ],
    "customer_data"=> [
      "mobile_number"=> "7350807077",
      "email_id"=> "darshan@teaminertia.com"
    ],
    "txn_data"=> [
    "navigation_mode"=> 2,
    "payment_mode"=> "1,3,10",
    "transaction_type"=> 1
    ]
  
];

$jsonRequest = json_encode($data);

$base64EncodedRequest = base64_encode($jsonRequest);

//echo $base64EncodedRequest;

//echo '<br>';

$request=array('request'=>$base64EncodedRequest);
$JSON_REQUEST=json_encode($request);

$secret_key=Hex2String($secret_key);
$strFormdata = $base64EncodedRequest;
$hash = strtoupper(hash_hmac('sha256', $strFormdata, $secret_key));//creating Hash

//echo 'x/verify '.$hash;
//exit;


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://pinepg.in/api/v2/accept/payment');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $JSON_REQUEST);
$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Cache-Control: no-cache';
$headers[] = 'X-Verify:'. $hash;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$decodeJson = json_decode($result);
//DFA($decodeJson);

if($decodeJson->response_code=='1')
{
  header('location:'.$decodeJson->redirect_url);
  exit;
}else{

exit;
}





?>